-- MySQL Script generated by MySQL Workbench
-- Mon Aug 18 17:17:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdproyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdproyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdproyecto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bdproyecto` ;

-- -----------------------------------------------------
-- Table `bdproyecto`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NULL,
  `telefono` CHAR(9) NULL,
  `ubicacion` VARCHAR(200) NULL,
  `horario` VARCHAR(200) NULL,
  `tiktok_url` VARCHAR(200) NULL,
  `facebook_url` VARCHAR(200) NULL,
  `instagram_url` VARCHAR(200) NULL,
  `video_pres_url` VARCHAR(200) NULL,
  `logo_url` VARCHAR(200) NULL,
  `portada_url` VARCHAR(200) NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdproyecto`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  `imagen_url` VARCHAR(200) NULL,
  `estado` CHAR(2) NOT NULL COMMENT 'Si o no',
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdproyecto`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `imagen_url` VARCHAR(200) NULL,
  `descripcion` VARCHAR(100) NULL,
  `estado` CHAR(2) NOT NULL COMMENT 'Si o no',
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `bdproyecto`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdproyecto`.`terminos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`terminos` (
  `id_terminos` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id_terminos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdproyecto`.`politicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`politicas` (
  `id_politicas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id_politicas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdproyecto`.`cupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`cupon` (
  `id_cupon` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `estado` CHAR(2) NOT NULL COMMENT 'Si o no',
  PRIMARY KEY (`id_cupon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdproyecto`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`administrador` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `contrasena` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdproyecto`.`cupon_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`cupon_producto` (
  `id_cupon_producto` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_cupon` INT NOT NULL,
  PRIMARY KEY (`id_cupon_producto`),
  INDEX `fk_producto_cupon_idx` (`id_producto` ASC) VISIBLE,
  INDEX `kf_cupon_producto_idx` (`id_cupon` ASC) VISIBLE,
  CONSTRAINT `fk_producto_cupon`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bdproyecto`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kf_cupon_producto`
    FOREIGN KEY (`id_cupon`)
    REFERENCES `bdproyecto`.`cupon` (`id_cupon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdproyecto`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdproyecto`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `nom_cliente` VARCHAR(100) NOT NULL,
  `telef_cliente` CHAR(9) NOT NULL,
  `direccion_envio` VARCHAR(200) NOT NULL,
  `observaciones` VARCHAR(200) NULL,
  `metodo_pago` VARCHAR(100) NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_producto_pedido_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_categoria_pedido_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_pedido`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bdproyecto`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_pedido`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `bdproyecto`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
